@startuml

title __PRACTICA3-F08's Class Diagram__\n

  namespace  {
    class AppUBFLIXParty {
    }
  }
  

  namespace  {
    class MainClient {
    }
  }
  

  namespace  {
    namespace b.edu.controller {
      class ub.edu.controller.ControladorGUI {
      }
    }
  }
  

  namespace  {
    namespace b.edu.controller {
      class ub.edu.controller.ControllerTESTS {
      }
    }
  }
  

  namespace  {
    namespace b.edu.controller {
      interface ub.edu.controller.IController {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.Artista {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.CarteraClients {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.CatalegSeries {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.Client {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.Episodi {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.Facade {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.FacadeClients {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.FacadeRegistre {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.FacadeSeries {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.Preferencia {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      interface ub.edu.model.RegisterSubject {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.Registre {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.Serie {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      namespace StrategyTOP {
        abstract class ub.edu.model.StrategyTOP.IterableStrategy {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      namespace StrategyTOP {
        class ub.edu.model.StrategyTOP.TOPValoracionsStrategy {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      namespace StrategyTOP {
        class ub.edu.model.StrategyTOP.TOPVisualitzacionsStrategy {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.Temporada {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.Usuari {
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      namespace Valoracions {
        class ub.edu.model.Valoracions.CorValoracio {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      namespace Valoracions {
        class ub.edu.model.Valoracions.EstrellasValoracio {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      namespace Valoracions {
        abstract class ub.edu.model.Valoracions.Valoracio {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      namespace Valoracions {
        class ub.edu.model.Valoracions.ValoracioFactory {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.model {
      class ub.edu.model.Visualitzacio {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      interface ub.edu.resources.dao.DAO {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      interface ub.edu.resources.dao.DAOArtista {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      interface ub.edu.resources.dao.DAOClient {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      interface ub.edu.resources.dao.DAOEpisodi {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      interface ub.edu.resources.dao.DAOFollowers {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      interface ub.edu.resources.dao.DAOFollowings {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      interface ub.edu.resources.dao.DAOPreferencia {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      interface ub.edu.resources.dao.DAOSerie {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      interface ub.edu.resources.dao.DAOTemporada {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      interface ub.edu.resources.dao.DAOUsuari {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      interface ub.edu.resources.dao.DAOValoracioCor {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      interface ub.edu.resources.dao.DAOValoracioEstrellas {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      interface ub.edu.resources.dao.DAOVisualitzacio {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      namespace MOCK {
        class ub.edu.resources.dao.MOCK.DAOArtistaMOCK {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      namespace MOCK {
        class ub.edu.resources.dao.MOCK.DAOClientMOCK {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      namespace MOCK {
        class ub.edu.resources.dao.MOCK.DAOEpisodiMOCK {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      namespace MOCK {
        class ub.edu.resources.dao.MOCK.DAOFollowersMOCK {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      namespace MOCK {
        class ub.edu.resources.dao.MOCK.DAOFollowingsMOCK {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      namespace MOCK {
        class ub.edu.resources.dao.MOCK.DAOPreferenciaMOCK {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      namespace MOCK {
        class ub.edu.resources.dao.MOCK.DAOSerieMOCK {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      namespace MOCK {
        class ub.edu.resources.dao.MOCK.DAOTemporadaMOCK {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      namespace MOCK {
        class ub.edu.resources.dao.MOCK.DAOUsuariMOCK {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      namespace MOCK {
        class ub.edu.resources.dao.MOCK.DAOValoracioCorMOCK {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      namespace MOCK {
        class ub.edu.resources.dao.MOCK.DAOValoracioEstrellaMOCK {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.dao {
      namespace MOCK {
        class ub.edu.resources.dao.MOCK.DAOVisualitzacioMOCK {
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.service {
      interface ub.edu.resources.service.AbstractFactoryData {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.service {
      class ub.edu.resources.service.DataService {
      }
    }
  }
  

  namespace  {
    namespace b.edu.resources.service {
      class ub.edu.resources.service.FactoryMOCK {
      }
    }
  }
  

  namespace  {
    namespace b.edu.view {
      class ub.edu.view.FerPost {
      }
    }
  }
  

  namespace  {
    namespace b.edu.view {
      class ub.edu.view.FormEpisodi {
      }
    }
  }
  

  namespace  {
    namespace b.edu.view {
      class ub.edu.view.FormPerfilUsuari {
      }
    }
  }
  

  namespace  {
    namespace b.edu.view {
      class ub.edu.view.FormReproduccio {
      }
    }
  }
  

  namespace  {
    namespace b.edu.view {
      class ub.edu.view.FormReproductorVideo {
      }
    }
  }
  

  namespace  {
    namespace b.edu.view {
      class ub.edu.view.FormUser {
      }
    }
  }
  

  namespace  {
    namespace b.edu.view {
      class ub.edu.view.FrmLogIn {
      }
    }
  }
  

  namespace  {
    namespace b.edu.view {
      class ub.edu.view.FrmRegistre {
      }
    }
  }
  

  namespace  {
    namespace b.edu.view {
      class ub.edu.view.FrmValoracio {
      }
    }
  }
  

  namespace  {
    namespace b.edu.view {
      class ub.edu.view.MediaControl {
      }
    }
  }
  

  namespace  {
    namespace b.edu.view {
      interface ub.edu.view.RegisterObserver {
      }
    }
  }
  

  namespace  {
    namespace b.edu.view {
      class ub.edu.view.UBFLIXParty {
      }
    }
  }
  

  AppUBFLIXParty o-- ub.edu.controller.IController : controller
  ub.edu.controller.ControladorGUI .up.|> ub.edu.controller.IController
  ub.edu.controller.ControladorGUI o-- ub.edu.model.Facade : facana
  ub.edu.controller.ControladorGUI o-- ub.edu.view.UBFLIXParty : view
  ub.edu.controller.ControllerTESTS .up.|> ub.edu.controller.IController
  ub.edu.controller.ControllerTESTS o-- ub.edu.model.Facade : facana
  ub.edu.model.Facade o-- ub.edu.resources.service.DataService : dataService
  ub.edu.model.Facade o-- ub.edu.model.FacadeClients : facadeClients
  ub.edu.model.Facade o-- ub.edu.model.FacadeRegistre : facadeRegistre
  ub.edu.model.Facade o-- ub.edu.model.FacadeSeries : facadeSeries
  ub.edu.model.FacadeClients o-- ub.edu.model.CarteraClients : carteraClients
  ub.edu.model.FacadeRegistre o-- ub.edu.model.Registre : registre
  ub.edu.model.FacadeSeries o-- ub.edu.model.CatalegSeries : catalegSeries
  ub.edu.model.Registre .up.|> ub.edu.model.RegisterSubject
  ub.edu.model.StrategyTOP.IterableStrategy .up.|> java.lang.Iterable
  ub.edu.model.StrategyTOP.TOPValoracionsStrategy -up-|> ub.edu.model.StrategyTOP.IterableStrategy
  ub.edu.model.StrategyTOP.TOPVisualitzacionsStrategy -up-|> ub.edu.model.StrategyTOP.IterableStrategy
  ub.edu.model.Valoracions.CorValoracio -up-|> ub.edu.model.Valoracions.Valoracio
  ub.edu.model.Valoracions.EstrellasValoracio -up-|> ub.edu.model.Valoracions.Valoracio
  ub.edu.resources.dao.MOCK.DAOArtistaMOCK .up.|> ub.edu.resources.dao.DAOArtista
  ub.edu.resources.dao.MOCK.DAOClientMOCK .up.|> ub.edu.resources.dao.DAOClient
  ub.edu.resources.dao.MOCK.DAOEpisodiMOCK .up.|> ub.edu.resources.dao.DAOEpisodi
  ub.edu.resources.dao.MOCK.DAOFollowersMOCK .up.|> ub.edu.resources.dao.DAOFollowers
  ub.edu.resources.dao.MOCK.DAOFollowingsMOCK .up.|> ub.edu.resources.dao.DAOFollowings
  ub.edu.resources.dao.MOCK.DAOPreferenciaMOCK .up.|> ub.edu.resources.dao.DAOPreferencia
  ub.edu.resources.dao.MOCK.DAOSerieMOCK .up.|> ub.edu.resources.dao.DAOSerie
  ub.edu.resources.dao.MOCK.DAOTemporadaMOCK .up.|> ub.edu.resources.dao.DAOTemporada
  ub.edu.resources.dao.MOCK.DAOUsuariMOCK .up.|> ub.edu.resources.dao.DAOUsuari
  ub.edu.resources.dao.MOCK.DAOValoracioCorMOCK .up.|> ub.edu.resources.dao.DAOValoracioCor
  ub.edu.resources.dao.MOCK.DAOValoracioEstrellaMOCK .up.|> ub.edu.resources.dao.DAOValoracioEstrellas
  ub.edu.resources.dao.MOCK.DAOVisualitzacioMOCK .up.|> ub.edu.resources.dao.DAOVisualitzacio
  ub.edu.resources.service.DataService o-- ub.edu.resources.dao.DAOArtista : artistaDAO
  ub.edu.resources.service.DataService o-- ub.edu.resources.dao.DAOClient : clientDAO
  ub.edu.resources.service.DataService o-- ub.edu.resources.dao.DAOEpisodi : episodiDAO
  ub.edu.resources.service.DataService o-- ub.edu.resources.dao.DAOFollowers : followersDAO
  ub.edu.resources.service.DataService o-- ub.edu.resources.dao.DAOFollowings : followingsDAO
  ub.edu.resources.service.DataService o-- ub.edu.resources.dao.DAOPreferencia : preferenciaDAO
  ub.edu.resources.service.DataService o-- ub.edu.resources.dao.DAOSerie : serieDAO
  ub.edu.resources.service.DataService o-- ub.edu.resources.dao.DAOTemporada : temporadaDAO
  ub.edu.resources.service.DataService o-- ub.edu.resources.dao.DAOUsuari : usuariDAO
  ub.edu.resources.service.DataService o-- ub.edu.resources.dao.DAOValoracioCor : valoracioCorDAO
  ub.edu.resources.service.DataService o-- ub.edu.resources.dao.DAOValoracioEstrellas : valoracioEstrellasDAO
  ub.edu.resources.service.DataService o-- ub.edu.resources.dao.DAOVisualitzacio : visualitzacioDAO
  ub.edu.resources.service.FactoryMOCK .up.|> ub.edu.resources.service.AbstractFactoryData
  ub.edu.view.FerPost -up-|> javax.swing.JDialog
  ub.edu.view.FormEpisodi -up-|> javax.swing.JDialog
  ub.edu.view.FormEpisodi o-- ub.edu.controller.IController : controller
  ub.edu.view.FormPerfilUsuari -up-|> javax.swing.JFrame
  ub.edu.view.FormPerfilUsuari o-- ub.edu.controller.IController : controller
  ub.edu.view.FormReproduccio -up-|> javax.swing.JDialog
  ub.edu.view.FormReproduccio o-- ub.edu.controller.IController : controller
  ub.edu.view.FormReproductorVideo -up-|> javax.swing.JDialog
  ub.edu.view.FormReproductorVideo o-- ub.edu.controller.IController : controller
  ub.edu.view.FormReproductorVideo o-- ub.edu.view.MediaControl : mediaControl
  ub.edu.view.FormUser -up-|> javax.swing.JDialog
  ub.edu.view.FormUser o-- ub.edu.controller.IController : controller
  ub.edu.view.FrmLogIn -up-|> javax.swing.JDialog
  ub.edu.view.FrmLogIn o-- ub.edu.controller.IController : controller
  ub.edu.view.FrmRegistre -up-|> javax.swing.JDialog
  ub.edu.view.FrmRegistre o-- ub.edu.controller.IController : controller
  ub.edu.view.FrmValoracio -up-|> javax.swing.JDialog
  ub.edu.view.FrmValoracio o-- ub.edu.controller.IController : controller
  ub.edu.view.MediaControl -up-|> javafx.scene.layout.BorderPane
  ub.edu.view.UBFLIXParty .up.|> ub.edu.view.RegisterObserver
  ub.edu.view.UBFLIXParty -up-|> javax.swing.JFrame
  ub.edu.view.UBFLIXParty o-- ub.edu.controller.IController : controller


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
